### ISSUE TITLE
pip でアップグレードに失敗する

### ISSUE THREAD

**Issue by todashuta** [saitoha/sentimental-skk#4]
`% pip install --upgrade sentimental-skk`
とした際、テストが失敗しているようでアップグレードができませんでした。
直後の ~/.pip/pip.log なんですが、長すぎたのでgistにアップしてリンクを書いておきます。

[https://gist.github.com/todashuta/8170857](https://gist.github.com/todashuta/8170857)

**Comment by saitoha** [comment]
いつもありがとうございます。この問題はすぐに再現しました。
その理由なんですが、設定に依存するテストを書いてしまっていました。
私がAZIKメインで使っていたので気づけず、非常に助かりました。
で、それ自体は0.0.114で直ったと思うんですが、手元のDebian環境では直らず、pipのエラーが出続けました。
どうもビルドディレクトリのキャッシュを削除する必要があるみたいでした。
$HOME/buildを消したら直ったんですが、こちらの環境だけの問題かもしれません。
gistのエラーが出た環境だと
 /private/var/folders/5m/yq6c7qcs5gl1x70cb907rzcm0000gn/T/pip_build_todashuta/
がビルドディレクトリに相当すると思います。

**Comment by todashuta** [comment]
アップグレードしてバージョン 0.0.116 がインストールできたのを確認しました。
いつも対応ありがとうございます。
